[build]
pre-build = [
    "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable",
    ". $HOME/.cargo/env",
    "cargo install --force --locked bindgen-cli && mv $HOME/.cargo/bin/bindgen /usr/bin",
    "rm -rf $HOME/.cargo"
]

[build.env]
passthrough = [
    "AWS_LC_SYS_CMAKE_BUILDER=1"
]

[target.aarch64-pc-windows-msvc.build]
# Windows 镜像下执行 PowerShell 命令
pre-build = [
    "Set-ExecutionPolicy Bypass -Scope Process -Force",
    "irm https://sh.rustup.rs | iex", # 安装 Rust
    "$env:Path += ';$env:USERPROFILE\\.cargo\\bin'",
    "cargo install --force --locked bindgen-cli"
]
