// This file is @generated by prost-build.
/// 登录回复
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginAck {
    /// @build_automatically_generate_message_id@  enum MsgId {None = 0; Id = 1002;}
    /// 自己的玩家id
    #[prost(uint32, tag = "1")]
    pub player_id: u32,
    /// 通道列表
    #[prost(message, repeated, tag = "2")]
    pub tunnel_list: ::prost::alloc::vec::Vec<super::class_def::Tunnel>,
    /// 转发连接绑定使用的临时 token
    #[prost(string, tag = "3")]
    pub transport_token: ::prost::alloc::string::String,
    /// 服务端允许的最大转发连接数，0 表示单连接模式
    #[prost(uint32, tag = "4")]
    pub transport_max_connections: u32,
    /// 转发连接空闲关闭时间（秒）
    #[prost(uint32, tag = "5")]
    pub transport_idle_timeout_secs: u32,
}
/// 管理员登录回复
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ManagementLoginAck {
    /// @build_automatically_generate_message_id@  enum MsgId {None = 0; Id = 1006;}
    /// 错误码 0成功
    #[prost(int32, tag = "1")]
    pub code: i32,
}
/// 修改通道通知
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModifyTunnelNtf {
    /// @build_automatically_generate_message_id@  enum MsgId {None = 0; Id = 1008;}
    /// 是否是删除通道，如果不是则表示新增或更新通道信息
    #[prost(bool, tag = "1")]
    pub is_delete: bool,
    /// 通道信息
    #[prost(message, optional, tag = "2")]
    pub tunnel: ::core::option::Option<super::class_def::Tunnel>,
}
/// 转发连接快速绑定回复
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BindTransportAck {
    /// @build_automatically_generate_message_id@  enum MsgId {None = 0; Id = 1012;}
    /// 绑定成功的玩家 ID
    #[prost(uint32, tag = "1")]
    pub player_id: u32,
    /// 服务端确认的连接 ID
    #[prost(uint64, tag = "2")]
    pub connection_id: u64,
    /// 转发连接空闲关闭时间（秒）
    #[prost(uint32, tag = "3")]
    pub transport_idle_timeout_secs: u32,
}
/// 服务端主动断开连接通知
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DisconnectNtf {
    /// @build_automatically_generate_message_id@  enum MsgId {None = 0; Id = 1014;}
    /// 断开原因
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
}
